input_path: "C:/Users/dkodurul_stu/Downloads/cortal/input"
output_path: "C:/Users/dkodurul_stu/Downloads/cortal/output"

processing_options:
  frames:
    method: "fps"
    params:
      fps: 1
    output_format: "png"
    resolution: "1920*1080"
  
  audio:
    format: "wav"
    bitrate: "192k"