preferences:
  extraction_method: "1"  # Options are "1", "2", "3"
  fps: 30  # Only used if extraction_method is "1"
  time_interval: 5.0  # Only used if extraction_method is "2"
  threshold: 0.5  # Only used if extraction_method is "3"
  image_format: "jpg"
  resolution: "1920x1080"
  audio:
    format: "mp3"
    bitrate: "192k"
    